<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Ce_PrescriptionPayment
 * @copyright  Copyright (c) 2013 codedge (http://www.codedge.de)
 * @author     Holger Lösken <post@codedge.de>
*/

/**
 * Select if you pay by prescription
 *
 * @see Ce_PrescriptionPayment_Block_Items
 */
?>

<div class="block">
    <div class="block-title">
        <h3>
            <strong>
                <?php echo $this->__('Do you want to pay by prescription?'); ?>
            </strong>
        </h3>
    </div>
    <div class="block-content">
        <p class="empty">
            <input type="radio" name="prescriptionpayment_choose_payment" value="0" <?php if(!$this->payByPrescription()){echo 'checked="checked"';} ?>>
            <?php echo $this->__('No, I don\'t want to pay by prescription'); ?>
            <br />
            <input type="radio" name="prescriptionpayment_choose_payment" value="1" <?php if($this->payByPrescription()){echo 'checked="checked"';} ?>>
            <?php echo $this->__('Yes, I want to pay by prescription'); ?>
            <input type="hidden" name="proceedtocheckout" value="1"/>
        </p>
    </div>
</div>