<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Ce_PrescriptionPayment
 * @copyright  Copyright (c) 2013 codedge (http://www.codedge.de)
 * @author     Holger Lösken <post@codedge.de>
*/
?>
<?php if ($this->isPossibleOnepageCheckout()):?>
        <button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button prescription-proceed-checkout btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?>><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
        <script type="text/javascript">
            if (typeof jQuery != 'undefined') {
                jQuery('.prescription-proceed-checkout').click(function() {
                    if(jQuery("input[name='prescriptionpayment_choose_payment']:checked").val() == 1) {

                        var n = jQuery("input[name='prescriptionpayment_select[]']:checked").length;
                        if(n == 0) {
                            alert('<?php echo $this->__('Please select at least one item!')?>');
                        } else {
                            jQuery('#prescriptionpayment-form').submit();
                        }
                    } else {
                        jQuery('#prescriptionpayment-form').submit();
                    }
                });
            }
        </script>
<?php endif?>
