<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Ce_PrescriptionPayment
 * @copyright  Copyright (c) 2013 codedge (http://www.codedge.de)
 * @author     Holger Lösken <post@codedge.de>
*/

/**
 * Shopping cart template
 *
 * @see Ce_PrescriptionPayment_Block_Items
 */
?>
<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Choose your products for prescription payment') ?></h1>
        <?php if(!$this->hasError()): ?>
            <ul class="checkout-types">
                <?php foreach ($this->getMethods('top_methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                        <li><?php echo $methodHtml; ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
    <div class="block">
        <p class="empty">
            <?php echo $this->__('For the following articles it is possible to pay them by prescription') ?>.
        </p>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form id="prescriptionpayment-form" action="<?php echo $this->getUrl('checkout/onepage') ?>" method="post">
        <?php echo $this->getChildHtml('choosepayment') ?>
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                <col width="1" />
                <col />
                <col width="1" />
                <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                    <col width="1" />
                <?php endif ?>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <col width="1" />
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <col width="1" />

                <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                <tr>
                    <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                    <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                    <?php endif ?>
                    <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
                    <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                    <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
                    <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Prescription Payment') ?></th>
                </tr>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                <?php endif; ?>
                </thead>
                <tfoot>
                <tr>
                    <td colspan="50" class="a-right">
                        <button type="button" title="<?php echo $this->__('Back to shopping cart') ?>" class="button btn-continue" onclick="setLocation('<?php echo Mage::getUrl('checkout/cart') ?>')"><span><span><?php echo $this->__('Back to shopping cart') ?></span></span></button>
                        <button type="button" class="button btn-update" title="<?php echo $this->__('Select all items for prescription payment'); ?>" name="select_all_prescription" ><span><?php echo $this->__('Select all'); ?></span></button>
                    </td>
                </tr>
                </tfoot>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
    <div class="cart-collaterals prescriptionpayment">
        <div class="col2-set">
            <div class="block block-prescriptionpayment hint">
                <div class="block-title">
                    <h3><strong><?php echo $this->__('Notice') ?></strong></h3>
                </div>
                <div class="block-content">
                    <p class="empty">
                        <strong>
                            <?php echo $this->__('Please send the prescriptions for the selected items to the following address') ?>:
                        </strong><br />
                        <?php echo nl2br($this->getAddress()); ?>
                        <br /><br />
                        <?php echo $this->__('Delivery essentially only takes place after your prescriptions and payment is received') ?>.
                    </p>
                </div>
            </div>
        </div>
        <?php if($this->useUploader()) : ?>
            <div class="upload-prescription totals">
                <form id="pp-upload-form" name="pp-upload-form" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('prescriptionpayment/items/upload')?>">
                    <div class="block block-upload-prescriptions">
                        <div class="block-title">
                            <h3 class="left"><strong><?php echo $this->__('Upload prescriptions') ?></strong></h3>
                            <?php if($this->getFileUploadMultiple()) : ?>
                            <span class="right add">+</span>
                            <?php endif ?>
                            <div class="clearer"></div>
                        </div>
                        <div class="block-content">
                            <p class="empty">
                                <span class="fileLbl"><?php echo $this->__('File')?>:</span>&nbsp;<input type="file" name="<?php echo $this->getFileUploadFieldName(); ?>" />
                                <button type="submit" title="Save"><span><?php echo $this->__('Submit')?></span></button><br />
                                <span class="accepted-file-types">
                                    <?php echo $this->__('Only the following file types are accepted: %s', $this->getAllowedFileTypes()); ?>
                                </span>
                            </p>
                        </div>
                    </div>
                </form>
            </div>
            <script type="text/javascript">
                // <![CDATA[
                jQuery(document).ready(function() {
                    // Submit form via ajax
                    jQuery('#pp-upload-form').ajaxForm({
                        success:    function() {
                            jQuery('.block-upload-prescriptions .block-content .empty')
                                .find('span.fileLbl:gt(0), input[type="file"]:gt(0)').remove();
                            jQuery('.block-upload-prescriptions .block-content .empty')
                                .find('input[name="<?php echo $this->getFileUploadFieldName(); ?>"]').val('');
                        }
                    });

                    // Adding new input fields
                    jQuery('.block-upload-prescriptions .add').click(function() {
                        jQuery('<br />').insertBefore('#pp-upload-form button[type="submit"]');
                        jQuery('<span />', {
                            text: '<?php echo $this->__('File')?>:',
                            class: 'fileLbl'
                        }).insertBefore('#pp-upload-form button[type="submit"]');
                        jQuery('<input>').attr({
                            type: 'file',
                            name: '<?php echo $this->getFileUploadFieldName(); ?>'
                        }).insertBefore('#pp-upload-form button[type="submit"]');
                    });
                });
                // ]]>
            </script>
        <?php endif ?>
    </div>
</div>